// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbeliSNU18DOvPKazaNobrp_5xYo9DwaQ',
    appId: '1:892248434003:web:88cf8dd20a7c2ddc63eda6',
    messagingSenderId: '892248434003',
    projectId: 'juniorise-spooky-community',
    authDomain: 'juniorise-spooky-community.firebaseapp.com',
    storageBucket: 'juniorise-spooky-community.appspot.com',
    measurementId: 'G-LXYMM851PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn4IK7ySHqwlpYqWjg9BPvHdXuB4HJcy4',
    appId: '1:892248434003:android:5bb82d5f9885bd2d63eda6',
    messagingSenderId: '892248434003',
    projectId: 'juniorise-spooky-community',
    storageBucket: 'juniorise-spooky-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8Q8SrWFufbf5uC7TPDVC9aDw4_aqvRw',
    appId: '1:892248434003:ios:11f9fdc507a648e763eda6',
    messagingSenderId: '892248434003',
    projectId: 'juniorise-spooky-community',
    storageBucket: 'juniorise-spooky-community.appspot.com',
    iosClientId: '892248434003-k8vffnaqm3vlp8uga62r8lrp7lgkdcm0.apps.googleusercontent.com',
    iosBundleId: 'com.juniorise.spooky.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8Q8SrWFufbf5uC7TPDVC9aDw4_aqvRw',
    appId: '1:892248434003:ios:c1c7f010daf9631363eda6',
    messagingSenderId: '892248434003',
    projectId: 'juniorise-spooky-community',
    storageBucket: 'juniorise-spooky-community.appspot.com',
    iosClientId: '892248434003-34uc2e5inp4l3fmcvd0bh12ao1sq4pv2.apps.googleusercontent.com',
    iosBundleId: 'com.juniorise.spooky',
  );
}
